export const MANIPAL_DEPARTMENTS = [
  "Accident and Emergency Care",
  "Cancer Care and Oncology",
  "Cardiology",
  "Cardiothoracic and Vascular Surgery",
  "Dialysis",
  "Gastrointestinal Science",
  "Laparoscopic Surgery",
  "Live Transplant Surgery",
  "Nephrology",
  "Neurology",
  "Neurosurgery",
  "Obstetrics and Gynaecology",
  "Organ Transplant",
  "Orthopedic Robotic Surgery",
  "Orthopedics",
  "Pediatric and Child Care",
  "Proctology",
  "Rheumatology",
  "Spine Care",
  "Urology",
  "Allergy and Immunology",
  "Anesthesiology Department",
  "Bariatric Surgery or Weight Loss Surgery",
  "Bone Marrow Transplantation",
  "Children's Airway and Swallowing Centre",
  "Clinical Pyschology",
  "Dental Medicine",
  "Dermatology",
  "Diabetes and Endocrinology",
  "Ear Nose Throat",
  "Electrophysiology",
  "Fetal Medicine",
  "General Medicine",
  "General Surgery",
  "Genetics",
  "Geriatric Medicine",
  "GI Surgery",
  "Growth and Hormone",
  "Gynaec Oncology",
  "Hand Surgery",
  "Hemato Oncology",
  "Hematology",
  "Hepatobiliary Surgery",
  "ICU and Critical Care",
  "Infectious Disease",
  "Internal Medicine",
  "Intraventional Radiology",
  "IVF and Infertility",
  "Kidney Transplantation",
  "Laboratory Medicine",
  "Lactation",
  "Medical Gastro",
  "Medical Oncology",
  "Microbiology",
  "Minimal Access Surgery",
  "Neonatology & NICU",
  "Nuclear Medicine",
  "Nutrition And Dietetics",
  "Ophthalmology",
  "Oral Maxillo Facial Surgery",
  "Paediatric Cancer Care",
  "Paediatric Cardiology",
  "Paediatric Endocrinology",
  "Paediatric General Surgery",
  "Paediatric Infectious Disease",
  "Paediatric Intensive Care Unit",
  "Paediatric Neurology",
  "Paediatric Surgery",
  "Paediatric Urology",
  "Pain Medicine",
  "Parkinson Disease and Movement Disorder",
  "Pathology",
  "Pediatric Bone Marrow Transplant",
  "Pharmacy",
  "Physical Medicine and Rehabilitation",
  "Physiotherapy",
  "Plastic And Cosmetic Surgery",
  "Podiatric Surgery",
  "Psychiatry",
  "Psychology",
  "Pulmonology (Respiratory and Sleep Medicine)",
  "Radiology",
  "Radiotherapy (Oncology Radiation)",
  "Rehabilitation Medicine",
  "Renal Sciences",
  "Reproductive Medicine",
  "Robotic Assisted Surgery",
  "Senior Care Program",
  "Sports Medicine",
  "Surgical Gastro",
  "Surgical Oncology",
  "Thoracic Surgery",
  "Transfusion Medicine",
  "Trauma Care",
  "Vascular and Endovascular Surgery",
];
