import { Doctor } from "./types";

export const MANIPAL_DOCTORS: Doctor[] = [
  {
    fullName: "Dr. Mark Davis",
    specialty: "Gastroenterologist",
    department: "Gastroenterology",
    short_description: "Expert in digestive system diseases and treatments.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Mark+Davis",
    id: 230,
  },
  {
    fullName: "Dr. Anna Martinez",
    specialty: "Hepatologist",
    department: "Gastroenterology",
    short_description:
      "Specializes in liver diseases and gastrointestinal health.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Anna+Martinez",
    id: 231,
  },
  {
    fullName: "Dr. David Wilson",
    specialty: "Pediatric Gastroenterologist",
    department: "Gastroenterology",
    short_description: "Experienced in gastrointestinal disorders in children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+David+Wilson",
    id: 232,
  },
  {
    fullName: "Dr. Sarah Johnson",
    specialty: "Pulmonologist",
    department: "Pulmonology",
    short_description: "Expert in respiratory system diseases and treatments.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Sarah+Johnson",
    id: 227,
  },
  {
    fullName: "Dr. Andrew Smith",
    specialty: "Pulmonary Specialist",
    department: "Pulmonology",
    short_description: "Specializes in lung conditions and respiratory health.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Andrew+Smith",
    id: 228,
  },
  {
    fullName: "Dr. Laura Williams",
    specialty: "Pediatric Pulmonologist",
    department: "Pulmonology",
    short_description: "Experienced in respiratory disorders in children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Laura+Williams",
    id: 229,
  },
  {
    fullName: "Dr. Alice Martin",
    specialty: "Emergency Physician",
    department: "Accident and Emergency Care",
    short_description: "Experienced in handling critical and emergency cases.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Alice+Martin",
    id: 1,
  },
  {
    fullName: "Dr. Bruce Wayne",
    specialty: "Trauma Surgeon",
    department: "Accident and Emergency Care",
    short_description: "Specialist in trauma surgery and emergency care.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Bruce+Wayne",
    id: 2,
  },
  {
    fullName: "Dr. Carol Danvers",
    specialty: "Critical Care Specialist",
    department: "Accident and Emergency Care",
    short_description: "Expert in critical care and emergency response.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Carol+Danvers",
    id: 3,
  },
  {
    fullName: "Dr. Diana Prince",
    specialty: "Oncologist",
    department: "Cancer Care and Oncology",
    short_description: "Experienced in cancer treatment and care.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Diana+Prince",
    id: 4,
  },
  {
    fullName: "Dr. Clark Kent",
    specialty: "Radiation Oncologist",
    department: "Cancer Care and Oncology",
    short_description: "Specialist in radiation therapy for cancer patients.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Clark+Kent",
    id: 5,
  },
  {
    fullName: "Dr. Barry Allen",
    specialty: "Medical Oncologist",
    department: "Cancer Care and Oncology",
    short_description: "Expert in chemotherapy and cancer treatment.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Barry+Allen",
    id: 6,
  },
  {
    fullName: "Dr. John Smith",
    specialty: "Cardiologist",
    department: "Cardiology",
    short_description: "Experienced in treating heart conditions.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+John+Smith",
    id: 7,
  },
  {
    fullName: "Dr. Emily Johnson",
    specialty: "Interventional Cardiologist",
    department: "Cardiology",
    short_description:
      "Specialist in interventional procedures for heart conditions.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Emily+Johnson",
    id: 8,
  },
  {
    fullName: "Dr. Michael Brown",
    specialty: "Pediatric Cardiologist",
    department: "Cardiology",
    short_description: "Expert in heart conditions in children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Michael+Brown",
    id: 9,
  },
  {
    fullName: "Dr. Jessica Davis",
    specialty: "Cardiothoracic Surgeon",
    department: "Cardiothoracic and Vascular Surgery",
    short_description: "Specializes in heart and chest surgeries.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Jessica+Davis",
    id: 10,
  },
  {
    fullName: "Dr. William Martinez",
    specialty: "Vascular Surgeon",
    department: "Cardiothoracic and Vascular Surgery",
    short_description: "Expert in vascular surgeries and treatments.",
    profile_picture:
      "https://via.placeholder.com/150?text=Dr.+William+Martinez",
    id: 11,
  },
  {
    fullName: "Dr. Linda Garcia",
    specialty: "Thoracic Surgeon",
    department: "Cardiothoracic and Vascular Surgery",
    short_description: "Specialist in surgeries of the chest.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Linda+Garcia",
    id: 12,
  },
  {
    fullName: "Dr. Robert Wilson",
    specialty: "Nephrologist",
    department: "Dialysis",
    short_description: "Experienced in kidney care and dialysis treatments.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Robert+Wilson",
    id: 13,
  },
  {
    fullName: "Dr. Patricia Lee",
    specialty: "Renal Specialist",
    department: "Dialysis",
    short_description: "Specialist in renal care and dialysis management.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Patricia+Lee",
    id: 14,
  },
  {
    fullName: "Dr. James Hernandez",
    specialty: "Dialysis Technician",
    department: "Dialysis",
    short_description: "Expert in dialysis procedures and patient care.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+James+Hernandez",
    id: 15,
  },
  {
    fullName: "Dr. Susan Clark",
    specialty: "Gastroenterologist",
    department: "Gastrointestinal Science",
    short_description: "Specialist in digestive system disorders.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Susan+Clark",
    id: 16,
  },
  {
    fullName: "Dr. Daniel Williams",
    specialty: "Hepatologist",
    department: "Gastrointestinal Science",
    short_description: "Expert in liver diseases and treatments.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Daniel+Williams",
    id: 17,
  },
  {
    fullName: "Dr. Karen Adams",
    specialty: "GI Surgeon",
    department: "Gastrointestinal Science",
    short_description: "Specializes in gastrointestinal surgeries.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Karen+Adams",
    id: 18,
  },
  {
    fullName: "Dr. George Miller",
    specialty: "Laparoscopic Surgeon",
    department: "Laparoscopic Surgery",
    short_description: "Expert in minimally invasive surgical techniques.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+George+Miller",
    id: 19,
  },
  {
    fullName: "Dr. Nancy Wilson",
    specialty: "General Surgeon",
    department: "Laparoscopic Surgery",
    short_description: "Experienced in laparoscopic and general surgeries.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Nancy+Wilson",
    id: 20,
  },
  {
    fullName: "Dr. Paul White",
    specialty: "Bariatric Surgeon",
    department: "Laparoscopic Surgery",
    short_description: "Specialist in weight loss surgeries.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Paul+White",
    id: 21,
  },
  {
    fullName: "Dr. Kevin Brown",
    specialty: "Transplant Surgeon",
    department: "Live Transplant Surgery",
    short_description: "Experienced in live organ transplantation.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Kevin+Brown",
    id: 22,
  },
  {
    fullName: "Dr. Lisa Green",
    specialty: "Hepatobiliary Surgeon",
    department: "Live Transplant Surgery",
    short_description: "Specialist in liver and bile duct surgeries.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Lisa+Green",
    id: 23,
  },
  {
    fullName: "Dr. Charles Anderson",
    specialty: "Renal Transplant Surgeon",
    department: "Live Transplant Surgery",
    short_description: "Expert in kidney transplant surgeries.",
    profile_picture:
      "https://via.placeholder.com/150?text=Dr.+Charles+Anderson",
    id: 24,
  },
  {
    fullName: "Dr. Laura Evans",
    specialty: "Nephrologist",
    department: "Nephrology",
    short_description: "Expert in kidney diseases and treatments.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Laura+Evans",
    id: 25,
  },
  {
    fullName: "Dr. Brian Harris",
    specialty: "Pediatric Nephrologist",
    department: "Nephrology",
    short_description: "Specializes in kidney diseases in children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Brian+Harris",
    id: 26,
  },
  {
    fullName: "Dr. Angela Parker",
    specialty: "Transplant Nephrologist",
    department: "Nephrology",
    short_description: "Specialist in kidney transplantation.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Angela+Parker",
    id: 27,
  },
  {
    fullName: "Dr. Richard Thompson",
    specialty: "Neurologist",
    department: "Neurology",
    short_description: "Expert in nervous system disorders.",
    profile_picture:
      "https://via.placeholder.com/150?text=Dr.+Richard+Thompson",
    id: 28,
  },
  {
    fullName: "Dr. Karen Lewis",
    specialty: "Pediatric Neurologist",
    department: "Neurology",
    short_description: "Specialist in neurological disorders in children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Karen+Lewis",
    id: 29,
  },
  {
    fullName: "Dr. Steven Walker",
    specialty: "Neurophysiologist",
    department: "Neurology",
    short_description: "Expert in neurological diagnostics and treatments.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Steven+Walker",
    id: 30,
  },
  {
    fullName: "Dr. Frank Moore",
    specialty: "Neurosurgeon",
    department: "Neurosurgery",
    short_description: "Specialist in brain and spinal surgeries.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Frank+Moore",
    id: 31,
  },
  {
    fullName: "Dr. Dorothy Clark",
    specialty: "Spine Surgeon",
    department: "Neurosurgery",
    short_description: "Experienced in spine surgeries and treatments.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Dorothy+Clark",
    id: 32,
  },
  {
    fullName: "Dr. Peter Wright",
    specialty: "Pediatric Neurosurgeon",
    department: "Neurosurgery",
    short_description: "Specialist in neurological surgeries for children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Peter+Wright",
    id: 33,
  },
  {
    fullName: "Dr. Patricia Lee",
    specialty: "Obstetrician",
    department: "Obstetrics and Gynaecology",
    short_description: "Experienced in pregnancy and childbirth care.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Patricia+Lee",
    id: 34,
  },
  {
    fullName: "Dr. Charles Adams",
    specialty: "Gynecologist",
    department: "Obstetrics and Gynaecology",
    short_description: "Specialist in women's reproductive health.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Charles+Adams",
    id: 35,
  },
  {
    fullName: "Dr. Mary Johnson",
    specialty: "Maternal-Fetal Medicine Specialist",
    department: "Obstetrics and Gynaecology",
    short_description: "Expert in high-risk pregnancies.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Mary+Johnson",
    id: 36,
  },
  {
    fullName: "Dr. Robert Smith",
    specialty: "Transplant Surgeon",
    department: "Organ Transplant",
    short_description: "Expert in organ transplantation surgeries.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Robert+Smith",
    id: 37,
  },
  {
    fullName: "Dr. Linda Brown",
    specialty: "Liver Transplant Specialist",
    department: "Organ Transplant",
    short_description: "Specializes in liver transplantation.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Linda+Brown",
    id: 38,
  },
  {
    fullName: "Dr. James Davis",
    specialty: "Kidney Transplant Specialist",
    department: "Organ Transplant",
    short_description: "Experienced in kidney transplantation procedures.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+James+Davis",
    id: 39,
  },
  {
    fullName: "Dr. Susan White",
    specialty: "Orthopedic Surgeon",
    department: "Orthopedic Robotic Surgery",
    short_description: "Expert in robotic-assisted orthopedic surgeries.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Susan+White",
    id: 40,
  },
  {
    fullName: "Dr. George Brown",
    specialty: "Robotic Surgeon",
    department: "Orthopedic Robotic Surgery",
    short_description: "Specialist in robotic surgery techniques.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+George+Brown",
    id: 41,
  },
  {
    fullName: "Dr. Emily Martinez",
    specialty: "Pediatric Orthopedic Surgeon",
    department: "Orthopedic Robotic Surgery",
    short_description: "Specializes in robotic surgeries for children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Emily+Martinez",
    id: 42,
  },
  {
    fullName: "Dr. John Wilson",
    specialty: "Orthopedic Surgeon",
    department: "Orthopedics",
    short_description: "Expert in musculoskeletal system surgeries.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+John+Wilson",
    id: 43,
  },
  {
    fullName: "Dr. Karen Johnson",
    specialty: "Sports Medicine Specialist",
    department: "Orthopedics",
    short_description: "Specialist in sports injuries and orthopedic care.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Karen+Johnson",
    id: 44,
  },
  {
    fullName: "Dr. Michael Martinez",
    specialty: "Joint Replacement Surgeon",
    department: "Orthopedics",
    short_description: "Expert in joint replacement surgeries.",
    profile_picture:
      "https://via.placeholder.com/150?text=Dr.+Michael+Martinez",
    id: 45,
  },
  {
    fullName: "Dr. Jessica Brown",
    specialty: "Pediatrician",
    department: "Pediatric and Child Care",
    short_description: "Focused on children's health and development.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Jessica+Brown",
    id: 46,
  },
  {
    fullName: "Dr. William Garcia",
    specialty: "Neonatologist",
    department: "Pediatric and Child Care",
    short_description: "Specializes in newborn care and treatments.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+William+Garcia",
    id: 47,
  },
  {
    fullName: "Dr. Linda Martinez",
    specialty: "Pediatric Surgeon",
    department: "Pediatric and Child Care",
    short_description: "Expert in surgical care for children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Linda+Martinez",
    id: 48,
  },
  {
    fullName: "Dr. Robert Harris",
    specialty: "Proctologist",
    department: "Proctology",
    short_description:
      "Experienced in treating conditions of the rectum and anus.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Robert+Harris",
    id: 49,
  },
  {
    fullName: "Dr. Patricia Davis",
    specialty: "Colorectal Surgeon",
    department: "Proctology",
    short_description: "Specialist in surgeries of the colon and rectum.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Patricia+Davis",
    id: 50,
  },
  {
    fullName: "Dr. James Clark",
    specialty: "Gastroenterologist",
    department: "Proctology",
    short_description: "Expert in gastrointestinal system disorders.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+James+Clark",
    id: 51,
  },
  {
    fullName: "Dr. Susan Lewis",
    specialty: "Rheumatologist",
    department: "Rheumatology",
    short_description:
      "Experienced in treating autoimmune and inflammatory diseases.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Susan+Lewis",
    id: 52,
  },
  {
    fullName: "Dr. Daniel White",
    specialty: "Pediatric Rheumatologist",
    department: "Rheumatology",
    short_description: "Specialist in rheumatic diseases in children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Daniel+White",
    id: 53,
  },
  {
    fullName: "Dr. Laura Robinson",
    specialty: "Immunologist",
    department: "Rheumatology",
    short_description: "Expert in immune system disorders.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Laura+Robinson",
    id: 54,
  },
  {
    fullName: "Dr. George Thompson",
    specialty: "Spine Surgeon",
    department: "Spine Care",
    short_description: "Expert in spine surgeries and treatments.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+George+Thompson",
    id: 55,
  },
  {
    fullName: "Dr. Emily Davis",
    specialty: "Orthopedic Surgeon",
    department: "Spine Care",
    short_description: "Specialist in spine and musculoskeletal disorders.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Emily+Davis",
    id: 56,
  },
  {
    fullName: "Dr. Michael Brown",
    specialty: "Neurosurgeon",
    department: "Spine Care",
    short_description: "Specializes in surgeries of the spine.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Michael+Brown",
    id: 57,
  },
  {
    fullName: "Dr. Linda Johnson",
    specialty: "Urologist",
    department: "Urology",
    short_description: "Experienced in urinary system treatments.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Linda+Johnson",
    id: 58,
  },
  {
    fullName: "Dr. Charles Harris",
    specialty: "Pediatric Urologist",
    department: "Urology",
    short_description: "Specializes in urological care for children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Charles+Harris",
    id: 59,
  },
  {
    fullName: "Dr. Nancy Williams",
    specialty: "Reconstructive Urologist",
    department: "Urology",
    short_description: "Expert in reconstructive urological surgeries.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Nancy+Williams",
    id: 60,
  },
  {
    fullName: "Dr. Richard Miller",
    specialty: "Allergist",
    department: "Allergy and Immunology",
    short_description: "Specialist in allergy and immune system disorders.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Richard+Miller",
    id: 61,
  },
  {
    fullName: "Dr. Angela Smith",
    specialty: "Immunologist",
    department: "Allergy and Immunology",
    short_description: "Expert in treating immune system diseases.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Angela+Smith",
    id: 62,
  },
  {
    fullName: "Dr. Brian Johnson",
    specialty: "Pediatric Allergist",
    department: "Allergy and Immunology",
    short_description: "Specializes in allergy treatments for children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Brian+Johnson",
    id: 63,
  },
  {
    fullName: "Dr. Emily Clark",
    specialty: "Anesthesiologist",
    department: "Anesthesiology Department",
    short_description: "Expert in anesthesia and pain management.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Emily+Clark",
    id: 64,
  },
  {
    fullName: "Dr. Kevin Brown",
    specialty: "Pain Management Specialist",
    department: "Anesthesiology Department",
    short_description: "Specialist in managing acute and chronic pain.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Kevin+Brown",
    id: 65,
  },
  {
    fullName: "Dr. Susan Lewis",
    specialty: "Pediatric Anesthesiologist",
    department: "Anesthesiology Department",
    short_description: "Experienced in anesthesia for pediatric patients.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Susan+Lewis",
    id: 66,
  },
  {
    fullName: "Dr. George White",
    specialty: "Bariatric Surgeon",
    department: "Bariatric Surgery or Weight Loss Surgery",
    short_description: "Expert in weight loss surgeries.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+George+White",
    id: 67,
  },
  {
    fullName: "Dr. Laura Davis",
    specialty: "Metabolic Specialist",
    department: "Bariatric Surgery or Weight Loss Surgery",
    short_description:
      "Specializes in metabolic disorders and weight management.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Laura+Davis",
    id: 68,
  },
  {
    fullName: "Dr. James Harris",
    specialty: "Endocrinologist",
    department: "Bariatric Surgery or Weight Loss Surgery",
    short_description: "Expert in hormonal and metabolic treatments.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+James+Harris",
    id: 69,
  },
  {
    fullName: "Dr. Patricia Moore",
    specialty: "Hematologist",
    department: "Bone Marrow Transplantation",
    short_description: "Expert in blood diseases and bone marrow transplants.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Patricia+Moore",
    id: 70,
  },
  {
    fullName: "Dr. Richard Johnson",
    specialty: "Oncologist",
    department: "Bone Marrow Transplantation",
    short_description:
      "Specializes in cancer treatment and bone marrow transplantation.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Richard+Johnson",
    id: 71,
  },
  {
    fullName: "Dr. Laura Wilson",
    specialty: "Pediatric Hematologist",
    department: "Bone Marrow Transplantation",
    short_description: "Experienced in bone marrow transplants for children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Laura+Wilson",
    id: 72,
  },
  {
    fullName: "Dr. Daniel Brown",
    specialty: "Pediatric Pulmonologist",
    department: "Children's Airway and Swallowing Centre",
    short_description: "Expert in respiratory disorders in children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Daniel+Brown",
    id: 73,
  },
  {
    fullName: "Dr. Linda White",
    specialty: "Speech-Language Pathologist",
    department: "Children's Airway and Swallowing Centre",
    short_description: "Specializes in speech and swallowing disorders.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Linda+White",
    id: 74,
  },
  {
    fullName: "Dr. Michael Green",
    specialty: "Pediatric Gastroenterologist",
    department: "Children's Airway and Swallowing Centre",
    short_description: "Experienced in gastrointestinal disorders in children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Michael+Green",
    id: 75,
  },
  {
    fullName: "Dr. Jessica Brown",
    specialty: "Clinical Psychologist",
    department: "Clinical Psychology",
    short_description: "Expert in mental health and psychological treatments.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Jessica+Brown",
    id: 76,
  },
  {
    fullName: "Dr. Robert Green",
    specialty: "Child Psychologist",
    department: "Clinical Psychology",
    short_description: "Specializes in psychological treatments for children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Robert+Green",
    id: 77,
  },
  {
    fullName: "Dr. Emily Harris",
    specialty: "Neuropsychologist",
    department: "Clinical Psychology",
    short_description: "Experienced in brain-behavior relationships.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Emily+Harris",
    id: 78,
  },
  {
    fullName: "Dr. George White",
    specialty: "Dentist",
    department: "Dental Medicine",
    short_description: "Expert in dental care and oral health.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+George+White",
    id: 79,
  },
  {
    fullName: "Dr. Laura Johnson",
    specialty: "Orthodontist",
    department: "Dental Medicine",
    short_description: "Specializes in correcting teeth and jaw alignment.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Laura+Johnson",
    id: 80,
  },
  {
    fullName: "Dr. James Brown",
    specialty: "Oral Surgeon",
    department: "Dental Medicine",
    short_description: "Experienced in surgeries of the mouth and jaw.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+James+Brown",
    id: 81,
  },
  {
    fullName: "Dr. Patricia White",
    specialty: "Dermatologist",
    department: "Dermatology",
    short_description: "Specialist in skin conditions and treatments.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Patricia+White",
    id: 82,
  },
  {
    fullName: "Dr. Richard Black",
    specialty: "Pediatric Dermatologist",
    department: "Dermatology",
    short_description: "Expert in skin conditions in children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Richard+Black",
    id: 83,
  },
  {
    fullName: "Dr. Linda Brown",
    specialty: "Cosmetic Dermatologist",
    department: "Dermatology",
    short_description: "Specializes in cosmetic skin treatments.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Linda+Brown",
    id: 84,
  },
  {
    fullName: "Dr. James Smith",
    specialty: "Endocrinologist",
    department: "Diabetes and Endocrinology",
    short_description: "Experienced in hormonal and metabolic disorders.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+James+Smith",
    id: 85,
  },
  {
    fullName: "Dr. Patricia Johnson",
    specialty: "Diabetologist",
    department: "Diabetes and Endocrinology",
    short_description: "Specializes in diabetes management and treatment.",
    profile_picture:
      "https://via.placeholder.com/150?text=Dr.+Patricia+Johnson",
    id: 86,
  },
  {
    fullName: "Dr. Michael Brown",
    specialty: "Pediatric Endocrinologist",
    department: "Diabetes and Endocrinology",
    short_description: "Expert in endocrine disorders in children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Michael+Brown",
    id: 87,
  },
  {
    fullName: "Dr. Susan Davis",
    specialty: "Otolaryngologist",
    department: "Ear Nose Throat",
    short_description: "Specialist in conditions of the ear, nose, and throat.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Susan+Davis",
    id: 88,
  },
  {
    fullName: "Dr. George White",
    specialty: "Pediatric ENT Specialist",
    department: "Ear Nose Throat",
    short_description: "Experienced in ENT conditions in children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+George+White",
    id: 89,
  },
  {
    fullName: "Dr. Patricia Black",
    specialty: "Rhinologist",
    department: "Ear Nose Throat",
    short_description: "Specializes in nose and sinus disorders.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Patricia+Black",
    id: 90,
  },
  {
    fullName: "Dr. Robert Brown",
    specialty: "Cardiologist",
    department: "Electrophysiology",
    short_description: "Specialist in heart rhythm disorders.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Robert+Brown",
    id: 91,
  },
  {
    fullName: "Dr. Linda Smith",
    specialty: "Electrophysiologist",
    department: "Electrophysiology",
    short_description: "Expert in electrophysiology and heart rhythms.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Linda+Smith",
    id: 92,
  },
  {
    fullName: "Dr. George Johnson",
    specialty: "Pediatric Electrophysiologist",
    department: "Electrophysiology",
    short_description: "Specializes in heart rhythm disorders in children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+George+Johnson",
    id: 93,
  },
  {
    fullName: "Dr. Jessica White",
    specialty: "Obstetrician",
    department: "Fetal Medicine",
    short_description: "Expert in fetal health and high-risk pregnancies.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Jessica+White",
    id: 94,
  },
  {
    fullName: "Dr. William Brown",
    specialty: "Fetal Surgeon",
    department: "Fetal Medicine",
    short_description: "Specializes in surgeries for fetal conditions.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+William+Brown",
    id: 95,
  },
  {
    fullName: "Dr. Linda Johnson",
    specialty: "Genetic Counselor",
    department: "Fetal Medicine",
    short_description: "Experienced in genetic counseling and fetal health.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Linda+Johnson",
    id: 96,
  },
  {
    fullName: "Dr. George Smith",
    specialty: "General Practitioner",
    department: "General Medicine",
    short_description: "Expert in primary care and general health.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+George+Smith",
    id: 97,
  },
  {
    fullName: "Dr. Jessica Brown",
    specialty: "Family Medicine Specialist",
    department: "General Medicine",
    short_description: "Specializes in family medicine and general health.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Jessica+Brown",
    id: 98,
  },
  {
    fullName: "Dr. William Johnson",
    specialty: "Internist",
    department: "General Medicine",
    short_description: "Experienced in internal medicine and diagnostics.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+William+Johnson",
    id: 99,
  },
  {
    fullName: "Dr. Patricia Brown",
    specialty: "General Surgeon",
    department: "General Surgery",
    short_description: "Specialist in general surgical procedures.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Patricia+Brown",
    id: 100,
  },
  {
    fullName: "Dr. Robert White",
    specialty: "Laparoscopic Surgeon",
    department: "General Surgery",
    short_description: "Expert in minimally invasive surgical techniques.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Robert+White",
    id: 101,
  },
  {
    fullName: "Dr. Linda Johnson",
    specialty: "Pediatric Surgeon",
    department: "General Surgery",
    short_description: "Specializes in general surgeries for children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Linda+Johnson",
    id: 102,
  },
  {
    fullName: "Dr. George Brown",
    specialty: "Geneticist",
    department: "Genetics",
    short_description: "Expert in genetic disorders and counseling.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+George+Brown",
    id: 103,
  },
  {
    fullName: "Dr. Jessica White",
    specialty: "Pediatric Geneticist",
    department: "Genetics",
    short_description: "Specializes in genetic disorders in children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Jessica+White",
    id: 104,
  },
  {
    fullName: "Dr. William Smith",
    specialty: "Molecular Geneticist",
    department: "Genetics",
    short_description: "Experienced in molecular genetics and diagnostics.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+William+Smith",
    id: 105,
  },
  {
    fullName: "Dr. Patricia Johnson",
    specialty: "Geriatrician",
    department: "Geriatric Medicine",
    short_description: "Expert in elderly care and geriatric health.",
    profile_picture:
      "https://via.placeholder.com/150?text=Dr.+Patricia+Johnson",
    id: 106,
  },
  {
    fullName: "Dr. Robert Brown",
    specialty: "Palliative Care Specialist",
    department: "Geriatric Medicine",
    short_description: "Specializes in palliative care for the elderly.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Robert+Brown",
    id: 107,
  },
  {
    fullName: "Dr. Linda White",
    specialty: "Geriatric Psychologist",
    department: "Geriatric Medicine",
    short_description: "Experienced in psychological care for the elderly.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Linda+White",
    id: 108,
  },
  {
    fullName: "Dr. George Johnson",
    specialty: "GI Surgeon",
    department: "GI Surgery",
    short_description: "Specializes in gastrointestinal surgeries.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+George+Johnson",
    id: 109,
  },
  {
    fullName: "Dr. Jessica Brown",
    specialty: "Laparoscopic Surgeon",
    department: "GI Surgery",
    short_description: "Expert in minimally invasive GI surgeries.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Jessica+Brown",
    id: 110,
  },
  {
    fullName: "Dr. William Smith",
    specialty: "Hepatobiliary Surgeon",
    department: "GI Surgery",
    short_description: "Experienced in liver and bile duct surgeries.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+William+Smith",
    id: 111,
  },
  {
    fullName: "Dr. Patricia Johnson",
    specialty: "Endocrinologist",
    department: "Growth and Hormone",
    short_description: "Specializes in growth and hormonal disorders.",
    profile_picture:
      "https://via.placeholder.com/150?text=Dr.+Patricia+Johnson",
    id: 112,
  },
  {
    fullName: "Dr. Robert Brown",
    specialty: "Pediatric Endocrinologist",
    department: "Growth and Hormone",
    short_description: "Expert in growth and hormone disorders in children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Robert+Brown",
    id: 113,
  },
  {
    fullName: "Dr. Linda White",
    specialty: "Reproductive Endocrinologist",
    department: "Growth and Hormone",
    short_description: "Experienced in reproductive hormonal treatments.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Linda+White",
    id: 114,
  },
  {
    fullName: "Dr. George Johnson",
    specialty: "Oncologist",
    department: "Gynaec Oncology",
    short_description: "Specialist in gynecological cancers.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+George+Johnson",
    id: 115,
  },
  {
    fullName: "Dr. Jessica Brown",
    specialty: "Gynecologist",
    department: "Gynaec Oncology",
    short_description: "Expert in gynecological health and cancer treatments.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Jessica+Brown",
    id: 116,
  },
  {
    fullName: "Dr. William Smith",
    specialty: "Radiation Oncologist",
    department: "Gynaec Oncology",
    short_description:
      "Experienced in radiation therapy for gynecological cancers.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+William+Smith",
    id: 117,
  },
  {
    fullName: "Dr. Patricia Johnson",
    specialty: "Hand Surgeon",
    department: "Hand Surgery",
    short_description: "Specializes in surgeries of the hand and wrist.",
    profile_picture:
      "https://via.placeholder.com/150?text=Dr.+Patricia+Johnson",
    id: 118,
  },
  {
    fullName: "Dr. Robert Brown",
    specialty: "Orthopedic Surgeon",
    department: "Hand Surgery",
    short_description: "Expert in hand and upper extremity surgeries.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Robert+Brown",
    id: 119,
  },
  {
    fullName: "Dr. Linda White",
    specialty: "Plastic Surgeon",
    department: "Hand Surgery",
    short_description: "Experienced in reconstructive surgeries of the hand.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Linda+White",
    id: 120,
  },
  {
    fullName: "Dr. George Johnson",
    specialty: "Hematologist",
    department: "Hemato Oncology",
    short_description: "Specialist in blood cancers and disorders.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+George+Johnson",
    id: 121,
  },
  {
    fullName: "Dr. Jessica Brown",
    specialty: "Oncologist",
    department: "Hemato Oncology",
    short_description: "Expert in cancer treatments and hematology.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Jessica+Brown",
    id: 122,
  },
  {
    fullName: "Dr. William Smith",
    specialty: "Pediatric Hematologist",
    department: "Hemato Oncology",
    short_description:
      "Experienced in blood disorders and cancers in children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+William+Smith",
    id: 123,
  },
  {
    fullName: "Dr. Patricia Johnson",
    specialty: "Hematologist",
    department: "Hematology",
    short_description: "Expert in blood disorders and treatments.",
    profile_picture:
      "https://via.placeholder.com/150?text=Dr.+Patricia+Johnson",
    id: 124,
  },
  {
    fullName: "Dr. Robert Brown",
    specialty: "Pediatric Hematologist",
    department: "Hematology",
    short_description: "Specializes in blood disorders in children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Robert+Brown",
    id: 125,
  },
  {
    fullName: "Dr. Linda White",
    specialty: "Oncologist",
    department: "Hematology",
    short_description: "Experienced in blood cancers and treatments.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Linda+White",
    id: 126,
  },
  {
    fullName: "Dr. George Johnson",
    specialty: "Hepatobiliary Surgeon",
    department: "Hepatobiliary Surgery",
    short_description: "Specialist in liver and bile duct surgeries.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+George+Johnson",
    id: 127,
  },
  {
    fullName: "Dr. Jessica Brown",
    specialty: "Gastroenterologist",
    department: "Hepatobiliary Surgery",
    short_description: "Expert in liver and digestive system disorders.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Jessica+Brown",
    id: 128,
  },
  {
    fullName: "Dr. William Smith",
    specialty: "Laparoscopic Surgeon",
    department: "Hepatobiliary Surgery",
    short_description: "Experienced in minimally invasive liver surgeries.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+William+Smith",
    id: 129,
  },
  {
    fullName: "Dr. Patricia Johnson",
    specialty: "Intensive Care Specialist",
    department: "ICU and Critical Care",
    short_description: "Expert in critical care and intensive treatments.",
    profile_picture:
      "https://via.placeholder.com/150?text=Dr.+Patricia+Johnson",
    id: 130,
  },
  {
    fullName: "Dr. Robert Brown",
    specialty: "Critical Care Surgeon",
    department: "ICU and Critical Care",
    short_description: "Specializes in surgeries for critically ill patients.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Robert+Brown",
    id: 131,
  },
  {
    fullName: "Dr. Linda White",
    specialty: "Pediatric Intensivist",
    department: "ICU and Critical Care",
    short_description: "Experienced in intensive care for children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Linda+White",
    id: 132,
  },
  {
    fullName: "Dr. George Johnson",
    specialty: "Infectious Disease Specialist",
    department: "Infectious Disease",
    short_description: "Expert in infectious diseases and treatments.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+George+Johnson",
    id: 133,
  },
  {
    fullName: "Dr. Jessica Brown",
    specialty: "Epidemiologist",
    department: "Infectious Disease",
    short_description: "Specializes in disease outbreaks and epidemiology.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Jessica+Brown",
    id: 134,
  },
  {
    fullName: "Dr. William Smith",
    specialty: "Pediatric Infectious Disease Specialist",
    department: "Infectious Disease",
    short_description: "Experienced in infectious diseases in children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+William+Smith",
    id: 135,
  },
  {
    fullName: "Dr. Patricia Johnson",
    specialty: "Internist",
    department: "Internal Medicine",
    short_description: "Expert in internal medicine and diagnostics.",
    profile_picture:
      "https://via.placeholder.com/150?text=Dr.+Patricia+Johnson",
    id: 136,
  },
  {
    fullName: "Dr. Robert Brown",
    specialty: "General Physician",
    department: "Internal Medicine",
    short_description: "Specializes in general and internal medicine.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Robert+Brown",
    id: 137,
  },
  {
    fullName: "Dr. Linda White",
    specialty: "Geriatric Internist",
    department: "Internal Medicine",
    short_description: "Experienced in internal medicine for the elderly.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Linda+White",
    id: 138,
  },
  {
    fullName: "Dr. George Johnson",
    specialty: "Interventional Radiologist",
    department: "Intraventional Radiology",
    short_description: "Specialist in minimally invasive radiology techniques.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+George+Johnson",
    id: 139,
  },
  {
    fullName: "Dr. Jessica Brown",
    specialty: "Diagnostic Radiologist",
    department: "Intraventional Radiology",
    short_description: "Expert in diagnostic imaging and radiology.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Jessica+Brown",
    id: 140,
  },
  {
    fullName: "Dr. William Smith",
    specialty: "Pediatric Radiologist",
    department: "Intraventional Radiology",
    short_description: "Experienced in radiology for pediatric patients.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+William+Smith",
    id: 141,
  },
  {
    fullName: "Dr. Patricia Johnson",
    specialty: "Reproductive Endocrinologist",
    department: "IVF and Infertility",
    short_description: "Expert in fertility treatments and IVF.",
    profile_picture:
      "https://via.placeholder.com/150?text=Dr.+Patricia+Johnson",
    id: 142,
  },
  {
    fullName: "Dr. Robert Brown",
    specialty: "Fertility Specialist",
    department: "IVF and Infertility",
    short_description:
      "Specializes in infertility treatments and reproductive health.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Robert+Brown",
    id: 143,
  },
  {
    fullName: "Dr. Linda White",
    specialty: "Pediatric Fertility Specialist",
    department: "IVF and Infertility",
    short_description:
      "Experienced in fertility treatments for young patients.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Linda+White",
    id: 144,
  },
  {
    fullName: "Dr. George Johnson",
    specialty: "Nephrologist",
    department: "Kidney Transplantation",
    short_description: "Expert in kidney transplants and treatments.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+George+Johnson",
    id: 145,
  },
  {
    fullName: "Dr. Jessica Brown",
    specialty: "Transplant Surgeon",
    department: "Kidney Transplantation",
    short_description: "Specializes in kidney transplant surgeries.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Jessica+Brown",
    id: 146,
  },
  {
    fullName: "Dr. William Smith",
    specialty: "Pediatric Nephrologist",
    department: "Kidney Transplantation",
    short_description: "Experienced in kidney transplants for children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+William+Smith",
    id: 147,
  },
  {
    fullName: "Dr. Patricia Johnson",
    specialty: "Pathologist",
    department: "Laboratory Medicine",
    short_description: "Expert in laboratory diagnostics and pathology.",
    profile_picture:
      "https://via.placeholder.com/150?text=Dr.+Patricia+Johnson",
    id: 148,
  },
  {
    fullName: "Dr. Robert Brown",
    specialty: "Clinical Laboratory Scientist",
    department: "Laboratory Medicine",
    short_description:
      "Specializes in clinical laboratory testing and analysis.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Robert+Brown",
    id: 149,
  },
  {
    fullName: "Dr. Linda White",
    specialty: "Microbiologist",
    department: "Laboratory Medicine",
    short_description: "Experienced in microbiological diagnostics.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Linda+White",
    id: 150,
  },
  {
    fullName: "Dr. George Johnson",
    specialty: "Lactation Consultant",
    department: "Lactation",
    short_description: "Expert in lactation and breastfeeding support.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+George+Johnson",
    id: 151,
  },
  {
    fullName: "Dr. Jessica Brown",
    specialty: "Pediatrician",
    department: "Lactation",
    short_description: "Specializes in breastfeeding and infant nutrition.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Jessica+Brown",
    id: 152,
  },
  {
    fullName: "Dr. William Smith",
    specialty: "Obstetrician",
    department: "Lactation",
    short_description: "Experienced in lactation support for new mothers.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+William+Smith",
    id: 153,
  },
  {
    fullName: "Dr. Patricia Johnson",
    specialty: "Gastroenterologist",
    department: "Medical Gastro",
    short_description: "Expert in gastrointestinal diseases and treatments.",
    profile_picture:
      "https://via.placeholder.com/150?text=Dr.+Patricia+Johnson",
    id: 154,
  },
  {
    fullName: "Dr. Robert Brown",
    specialty: "Hepatologist",
    department: "Medical Gastro",
    short_description:
      "Specializes in liver diseases and gastrointestinal health.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Robert+Brown",
    id: 155,
  },
  {
    fullName: "Dr. Linda White",
    specialty: "GI Surgeon",
    department: "Medical Gastro",
    short_description: "Experienced in gastrointestinal surgeries.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Linda+White",
    id: 156,
  },
  {
    fullName: "Dr. George Johnson",
    specialty: "Oncologist",
    department: "Medical Oncology",
    short_description: "Expert in cancer treatment and care.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+George+Johnson",
    id: 157,
  },
  {
    fullName: "Dr. Jessica Brown",
    specialty: "Radiation Oncologist",
    department: "Medical Oncology",
    short_description: "Specializes in radiation therapy for cancer patients.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Jessica+Brown",
    id: 158,
  },
  {
    fullName: "Dr. William Smith",
    specialty: "Hematologist",
    department: "Medical Oncology",
    short_description: "Experienced in blood cancers and treatments.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+William+Smith",
    id: 159,
  },
  {
    fullName: "Dr. Patricia Johnson",
    specialty: "Microbiologist",
    department: "Microbiology",
    short_description: "Expert in microbiological diagnostics and research.",
    profile_picture:
      "https://via.placeholder.com/150?text=Dr.+Patricia+Johnson",
    id: 160,
  },
  {
    fullName: "Dr. Robert Brown",
    specialty: "Clinical Microbiologist",
    department: "Microbiology",
    short_description:
      "Specializes in clinical microbiology and infectious diseases.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Robert+Brown",
    id: 161,
  },
  {
    fullName: "Dr. Linda White",
    specialty: "Virologist",
    department: "Microbiology",
    short_description: "Experienced in virology and virus research.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Linda+White",
    id: 162,
  },
  {
    fullName: "Dr. George Johnson",
    specialty: "Laparoscopic Surgeon",
    department: "Minimal Access Surgery",
    short_description: "Expert in minimally invasive surgical techniques.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+George+Johnson",
    id: 163,
  },
  {
    fullName: "Dr. Jessica Brown",
    specialty: "Bariatric Surgeon",
    department: "Minimal Access Surgery",
    short_description:
      "Specializes in weight loss surgeries using minimal access techniques.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Jessica+Brown",
    id: 164,
  },
  {
    fullName: "Dr. William Smith",
    specialty: "GI Surgeon",
    department: "Minimal Access Surgery",
    short_description:
      "Experienced in minimally invasive gastrointestinal surgeries.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+William+Smith",
    id: 165,
  },
  {
    fullName: "Dr. Patricia Johnson",
    specialty: "Neonatologist",
    department: "Neonatology & NICU",
    short_description: "Expert in newborn care and neonatal intensive care.",
    profile_picture:
      "https://via.placeholder.com/150?text=Dr.+Patricia+Johnson",
    id: 166,
  },
  {
    fullName: "Dr. Robert Brown",
    specialty: "Pediatrician",
    department: "Neonatology & NICU",
    short_description: "Specializes in newborn health and development.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Robert+Brown",
    id: 167,
  },
  {
    fullName: "Dr. Linda White",
    specialty: "Pediatric Surgeon",
    department: "Neonatology & NICU",
    short_description: "Experienced in surgeries for newborns and infants.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Linda+White",
    id: 168,
  },
  {
    fullName: "Dr. George Johnson",
    specialty: "Nuclear Medicine Specialist",
    department: "Nuclear Medicine",
    short_description: "Expert in nuclear medicine and imaging techniques.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+George+Johnson",
    id: 169,
  },
  {
    fullName: "Dr. Jessica Brown",
    specialty: "Radiologist",
    department: "Nuclear Medicine",
    short_description:
      "Specializes in radiology and nuclear medicine diagnostics.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Jessica+Brown",
    id: 170,
  },
  {
    fullName: "Dr. William Smith",
    specialty: "Oncologist",
    department: "Nuclear Medicine",
    short_description:
      "Experienced in cancer diagnostics using nuclear medicine.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+William+Smith",
    id: 171,
  },
  {
    fullName: "Dr. Patricia Johnson",
    specialty: "Dietitian",
    department: "Nutrition And Dietetics",
    short_description: "Expert in nutrition and dietary planning.",
    profile_picture:
      "https://via.placeholder.com/150?text=Dr.+Patricia+Johnson",
    id: 172,
  },
  {
    fullName: "Dr. Robert Brown",
    specialty: "Clinical Nutritionist",
    department: "Nutrition And Dietetics",
    short_description: "Specializes in clinical nutrition and dietary therapy.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Robert+Brown",
    id: 173,
  },
  {
    fullName: "Dr. Linda White",
    specialty: "Pediatric Nutritionist",
    department: "Nutrition And Dietetics",
    short_description: "Experienced in nutrition for children and adolescents.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Linda+White",
    id: 174,
  },
  {
    fullName: "Dr. George Johnson",
    specialty: "Ophthalmologist",
    department: "Ophthalmology",
    short_description: "Specializes in eye care and vision health.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+George+Johnson",
    id: 175,
  },
  {
    fullName: "Dr. Jessica Brown",
    specialty: "Retina Specialist",
    department: "Ophthalmology",
    short_description: "Expert in retina disorders and treatments.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Jessica+Brown",
    id: 176,
  },
  {
    fullName: "Dr. William Smith",
    specialty: "Pediatric Ophthalmologist",
    department: "Ophthalmology",
    short_description: "Experienced in eye care for children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+William+Smith",
    id: 177,
  },
  {
    fullName: "Dr. Patricia Johnson",
    specialty: "Oral Surgeon",
    department: "Oral Maxillo Facial Surgery",
    short_description: "Expert in surgeries of the mouth, jaw, and face.",
    profile_picture:
      "https://via.placeholder.com/150?text=Dr.+Patricia+Johnson",
    id: 178,
  },
  {
    fullName: "Dr. Robert Brown",
    specialty: "Maxillofacial Surgeon",
    department: "Oral Maxillo Facial Surgery",
    short_description: "Specializes in reconstructive surgeries of the face.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Robert+Brown",
    id: 179,
  },
  {
    fullName: "Dr. Linda White",
    specialty: "Dental Surgeon",
    department: "Oral Maxillo Facial Surgery",
    short_description: "Experienced in dental surgeries and oral health.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Linda+White",
    id: 180,
  },
  {
    fullName: "Dr. George Johnson",
    specialty: "Pediatric Oncologist",
    department: "Paediatric Cancer Care",
    short_description: "Expert in cancer treatments for children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+George+Johnson",
    id: 181,
  },
  {
    fullName: "Dr. Jessica Brown",
    specialty: "Hematologist",
    department: "Paediatric Cancer Care",
    short_description: "Specializes in blood cancers in pediatric patients.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Jessica+Brown",
    id: 182,
  },
  {
    fullName: "Dr. William Smith",
    specialty: "Radiation Oncologist",
    department: "Paediatric Cancer Care",
    short_description:
      "Experienced in radiation therapy for pediatric cancer patients.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+William+Smith",
    id: 183,
  },
  {
    fullName: "Dr. Patricia Johnson",
    specialty: "Pediatric Cardiologist",
    department: "Paediatric Cardiology",
    short_description: "Expert in heart conditions in children.",
    profile_picture:
      "https://via.placeholder.com/150?text=Dr.+Patricia+Johnson",
    id: 184,
  },
  {
    fullName: "Dr. Robert Brown",
    specialty: "Pediatric Cardiac Surgeon",
    department: "Paediatric Cardiology",
    short_description: "Specializes in heart surgeries for children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Robert+Brown",
    id: 185,
  },
  {
    fullName: "Dr. Linda White",
    specialty: "Electrophysiologist",
    department: "Paediatric Cardiology",
    short_description:
      "Experienced in heart rhythm disorders in pediatric patients.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Linda+White",
    id: 186,
  },
  {
    fullName: "Dr. George Johnson",
    specialty: "Pediatric Endocrinologist",
    department: "Paediatric Endocrinology",
    short_description: "Expert in hormonal disorders in children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+George+Johnson",
    id: 187,
  },
  {
    fullName: "Dr. Jessica Brown",
    specialty: "Diabetologist",
    department: "Paediatric Endocrinology",
    short_description:
      "Specializes in diabetes management for pediatric patients.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Jessica+Brown",
    id: 188,
  },
  {
    fullName: "Dr. William Smith",
    specialty: "Growth Specialist",
    department: "Paediatric Endocrinology",
    short_description:
      "Experienced in growth and development disorders in children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+William+Smith",
    id: 189,
  },
  {
    fullName: "Dr. Patricia Johnson",
    specialty: "Pediatric Surgeon",
    department: "Paediatric General Surgery",
    short_description: "Expert in general surgeries for children.",
    profile_picture:
      "https://via.placeholder.com/150?text=Dr.+Patricia+Johnson",
    id: 190,
  },
  {
    fullName: "Dr. Robert Brown",
    specialty: "Pediatric Urologist",
    department: "Paediatric General Surgery",
    short_description:
      "Specializes in urological surgeries for pediatric patients.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Robert+Brown",
    id: 191,
  },
  {
    fullName: "Dr. Linda White",
    specialty: "Pediatric ENT Surgeon",
    department: "Paediatric General Surgery",
    short_description: "Experienced in ENT surgeries for children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Linda+White",
    id: 192,
  },
  {
    fullName: "Dr. George Johnson",
    specialty: "Pediatric Infectious Disease Specialist",
    department: "Paediatric Infectious Disease",
    short_description: "Expert in infectious diseases in children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+George+Johnson",
    id: 193,
  },
  {
    fullName: "Dr. Jessica Brown",
    specialty: "Pediatric Epidemiologist",
    department: "Paediatric Infectious Disease",
    short_description:
      "Specializes in disease outbreaks and epidemiology in pediatric patients.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Jessica+Brown",
    id: 194,
  },
  {
    fullName: "Dr. William Smith",
    specialty: "Pediatric Virologist",
    department: "Paediatric Infectious Disease",
    short_description:
      "Experienced in viral infections and treatments for children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+William+Smith",
    id: 195,
  },
  {
    fullName: "Dr. Patricia Johnson",
    specialty: "Pediatric Intensivist",
    department: "Paediatric Intensive Care Unit",
    short_description: "Expert in intensive care for pediatric patients.",
    profile_picture:
      "https://via.placeholder.com/150?text=Dr.+Patricia+Johnson",
    id: 196,
  },
  {
    fullName: "Dr. Robert Brown",
    specialty: "Pediatric Surgeon",
    department: "Paediatric Intensive Care Unit",
    short_description: "Specializes in surgeries for critically ill children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Robert+Brown",
    id: 197,
  },
  {
    fullName: "Dr. Linda White",
    specialty: "Pediatric Critical Care Specialist",
    department: "Paediatric Intensive Care Unit",
    short_description: "Experienced in critical care treatments for children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Linda+White",
    id: 198,
  },
  {
    fullName: "Dr. George Johnson",
    specialty: "Pediatric Neurologist",
    department: "Paediatric Neurology",
    short_description: "Expert in neurological disorders in children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+George+Johnson",
    id: 199,
  },
  {
    fullName: "Dr. Jessica Brown",
    specialty: "Pediatric Epileptologist",
    department: "Paediatric Neurology",
    short_description:
      "Specializes in epilepsy and seizure disorders in pediatric patients.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Jessica+Brown",
    id: 200,
  },
  {
    fullName: "Dr. William Smith",
    specialty: "Pediatric Neurogeneticist",
    department: "Paediatric Neurology",
    short_description:
      "Experienced in genetic neurological disorders in children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+William+Smith",
    id: 201,
  },
  {
    fullName: "Dr. Patricia Johnson",
    specialty: "Pediatric Surgeon",
    department: "Paediatric Surgery",
    short_description: "Expert in surgical care for children.",
    profile_picture:
      "https://via.placeholder.com/150?text=Dr.+Patricia+Johnson",
    id: 202,
  },
  {
    fullName: "Dr. Robert Brown",
    specialty: "Pediatric Urologist",
    department: "Paediatric Surgery",
    short_description:
      "Specializes in urological surgeries for pediatric patients.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Robert+Brown",
    id: 203,
  },
  {
    fullName: "Dr. Linda White",
    specialty: "Pediatric ENT Surgeon",
    department: "Paediatric Surgery",
    short_description: "Experienced in ENT surgeries for children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Linda+White",
    id: 204,
  },
  {
    fullName: "Dr. George Johnson",
    specialty: "Pediatric Urologist",
    department: "Paediatric Urology",
    short_description: "Expert in urological care for children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+George+Johnson",
    id: 205,
  },
  {
    fullName: "Dr. Jessica Brown",
    specialty: "Pediatric Nephrologist",
    department: "Paediatric Urology",
    short_description:
      "Specializes in kidney and urinary tract disorders in children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Jessica+Brown",
    id: 206,
  },
  {
    fullName: "Dr. William Smith",
    specialty: "Pediatric Surgeon",
    department: "Paediatric Urology",
    short_description:
      "Experienced in surgeries for pediatric urological conditions.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+William+Smith",
    id: 207,
  },
  {
    fullName: "Dr. Patricia Johnson",
    specialty: "Pain Management Specialist",
    department: "Pain Medicine",
    short_description: "Expert in managing acute and chronic pain.",
    profile_picture:
      "https://via.placeholder.com/150?text=Dr.+Patricia+Johnson",
    id: 208,
  },
  {
    fullName: "Dr. Robert Brown",
    specialty: "Anesthesiologist",
    department: "Pain Medicine",
    short_description: "Specializes in anesthesia and pain management.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Robert+Brown",
    id: 209,
  },
  {
    fullName: "Dr. Linda White",
    specialty: "Pediatric Pain Specialist",
    department: "Pain Medicine",
    short_description: "Experienced in pain management for pediatric patients.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Linda+White",
    id: 210,
  },
  {
    fullName: "Dr. George Johnson",
    specialty: "Neurologist",
    department: "Parkinson Disease and Movement Disorder",
    short_description: "Expert in movement disorders and Parkinson's disease.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+George+Johnson",
    id: 211,
  },
  {
    fullName: "Dr. Jessica Brown",
    specialty: "Movement Disorder Specialist",
    department: "Parkinson Disease and Movement Disorder",
    short_description:
      "Specializes in movement disorders and neurological treatments.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Jessica+Brown",
    id: 212,
  },
  {
    fullName: "Dr. William Smith",
    specialty: "Geriatric Neurologist",
    department: "Parkinson Disease and Movement Disorder",
    short_description:
      "Experienced in neurological disorders in elderly patients.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+William+Smith",
    id: 213,
  },
  {
    fullName: "Dr. Patricia Johnson",
    specialty: "Pathologist",
    department: "Pathology",
    short_description:
      "Expert in diagnosing diseases through laboratory analysis.",
    profile_picture:
      "https://via.placeholder.com/150?text=Dr.+Patricia+Johnson",
    id: 214,
  },
  {
    fullName: "Dr. Robert Brown",
    specialty: "Clinical Pathologist",
    department: "Pathology",
    short_description: "Specializes in clinical pathology and diagnostics.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Robert+Brown",
    id: 215,
  },
  {
    fullName: "Dr. Linda White",
    specialty: "Forensic Pathologist",
    department: "Pathology",
    short_description: "Experienced in forensic pathology and autopsies.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Linda+White",
    id: 216,
  },
  {
    fullName: "Dr. George Johnson",
    specialty: "Hematologist",
    department: "Pediatric Bone Marrow Transplant",
    short_description:
      "Expert in bone marrow transplants for pediatric patients.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+George+Johnson",
    id: 217,
  },
  {
    fullName: "Dr. Jessica Brown",
    specialty: "Oncologist",
    department: "Pediatric Bone Marrow Transplant",
    short_description:
      "Specializes in cancer treatments and bone marrow transplants for children.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Jessica+Brown",
    id: 218,
  },
  {
    fullName: "Dr. William Smith",
    specialty: "Transplant Surgeon",
    department: "Pediatric Bone Marrow Transplant",
    short_description:
      "Experienced in bone marrow transplant surgeries for pediatric patients.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+William+Smith",
    id: 219,
  },
  {
    fullName: "Dr. Patricia Johnson",
    specialty: "Pharmacist",
    department: "Pharmacy",
    short_description:
      "Expert in pharmaceutical care and medication management.",
    profile_picture:
      "https://via.placeholder.com/150?text=Dr.+Patricia+Johnson",
    id: 220,
  },
  {
    fullName: "Dr. Robert Brown",
    specialty: "Clinical Pharmacist",
    department: "Pharmacy",
    short_description: "Specializes in clinical pharmacy and patient care.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Robert+Brown",
    id: 221,
  },
  {
    fullName: "Dr. Linda White",
    specialty: "Pediatric Pharmacist",
    department: "Pharmacy",
    short_description:
      "Experienced in medication management for pediatric patients.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Linda+White",
    id: 222,
  },
  {
    fullName: "Dr. George Johnson",
    specialty: "Physiatrist",
    department: "Physical Medicine and Rehabilitation",
    short_description: "Expert in physical medicine and rehabilitation.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+George+Johnson",
    id: 223,
  },
  {
    fullName: "Dr. Jessica Brown",
    specialty: "Rehabilitation Specialist",
    department: "Physical Medicine and Rehabilitation",
    short_description:
      "Specializes in rehabilitation therapies and treatments.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Jessica+Brown",
    id: 224,
  },
  {
    fullName: "Dr. William Smith",
    specialty: "Pediatric Physiatrist",
    department: "Physical Medicine and Rehabilitation",
    short_description: "Experienced in rehabilitation for pediatric patients.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+William+Smith",
    id: 225,
  },
  {
    fullName: "Dr. Patricia Johnson",
    specialty: "Physiotherapist",
    department: "Physiotherapy",
    short_description: "Expert in physical therapy and rehabilitation.",
    profile_picture:
      "https://via.placeholder.com/150?text=Dr.+Patricia+Johnson",
    id: 226,
  },
  {
    fullName: "Dr. Robert Brown",
    specialty: "Sports Physiotherapist",
    department: "Physiotherapy",
    short_description: "Specializes in sports injuries and physical therapy.",
    profile_picture: "https://via.placeholder.com/150?text=Dr.+Robert+Brown",
    id: 227,
  },
];
